apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-application
spec:
  chart:
    spec:
      sourceRef:
        name: podinfo
        namespace: ghc-nsp-e8347807-main-app
      version: 6.16.1
  install:
    remediation:
      retries: 3
  releaseName: podinfo
  serviceAccountName: ghc-nsp-e8347807-main-app-flux
  upgrade:
    remediation:
      retries: 3
  values:
    applicationName: podinfo
    deployment:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      image:
        repository: ghcr.io/stefanprodan/podinfo
        tag: 6.7.1
      ports:
        - containerPort: 9898
          name: http
      replicas: 1
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    ingress:
      enabled: false
    rbac:
      serviceAccount:
        enabled: false
        name: ghc-nsp-e8347807-main-app-workload
    service:
      ports:
        - name: http
          port: 9898
          targetPort: 9898
      type: ClusterIP
