- op: replace
  path: /metadata/name
  value: podinfo
- op: replace
  path: /metadata/namespace
  value: ghc-nsp-e8347807-main-app
- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: cluster-issuer
- op: replace
  path: /spec/rules/0/host
  value: podinfo.e8347807.dev.gh0stcloud.de
- op: replace
  path: /spec/rules/0/http/paths/0/backend/service/name
  value: podinfo
- op: replace
  path: /spec/rules/0/http/paths/0/backend/service/port/number
  value: 9898
- op: replace
  path: /spec/tls/0/hosts/0
  value: podinfo.e8347807.dev.gh0stcloud.de
- op: add
  path: /spec/tls/0/secretName
  value: podinfo-tls
