tenant:
  runtimeNamespace: ghc-nsp-8e31b964-main-notes
  workloadServiceAccount: ghc-nsp-8e31b964-main-notes-workload

host: notes.8e31b964.dev.gh0stcloud.de
clusterIssuer: cluster-issuer
registrySecretName: notes-registry-pull

backend:
  image:
    repository: ghcr.io/empireforge-ef/notes-backend
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

frontend:
  image:
    repository: ghcr.io/empireforge-ef/notes-frontend
    tag: latest
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

envoy:
  image:
    repository: envoyproxy/envoy
    tag: v1.31-latest
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

db:
  name: notes-db
  database: notes
  storageSize: 2Gi
  storageClass: hcloud-volumes
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

secrets:
  secretStore: ghc-ss-8e31b964-notes
  kvPath: tenants/8e31b964/app/main/notes

auth:
  mode: local
  bootstrapAdminEmail: admin@notes.local
