apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.db.name }}
  labels:
    app.kubernetes.io/part-of: notes
spec:
  instances: 1
  bootstrap:
    initdb:
      database: {{ .Values.db.database }}
      owner: {{ .Values.db.database }}
      secret:
        name: notes-db-credentials
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  storage:
    size: {{ .Values.db.storageSize }}
    storageClass: {{ .Values.db.storageClass }}
  resources:
    {{- toYaml .Values.db.resources | nindent 4 }}
