apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend
  labels:
    app.kubernetes.io/name: notes-frontend
    app.kubernetes.io/part-of: notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: notes-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: notes-frontend
        app.kubernetes.io/part-of: notes
    spec:
      serviceAccountName: {{ .Values.tenant.workloadServiceAccount }}
      imagePullSecrets:
        - name: {{ .Values.registrySecretName }}
      securityContext:
        {{- include "notes.podSecurityContext" . | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NUXT_PUBLIC_GRPC_BASE_URL
              value: "https://{{ .Values.host }}/grpc"
            - name: NITRO_HOST
              value: "0.0.0.0"
            - name: NITRO_PORT
              value: "3000"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            {{- include "notes.containerSecurityContext" . | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
