apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notes-kc-db-credentials
  namespace: ghc-nsp-8e31b964-main-notes
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: SecretStore
    name: ghc-ss-8e31b964-notes
  target:
    name: notes-kc-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: keycloak
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: tenants/8e31b964/app/main/notes/kc-db
        property: password
