apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notes-registry-pull
  namespace: ghc-nsp-8e31b964-main-notes
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: SecretStore
    name: ghc-ss-8e31b964-notes
  target:
    name: notes-registry-pull
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ $auth := printf \"%s:%s\" .username .password | b64enc }}{\"auths\":{\"{{ .registry }}\":{\"username\":\"{{ .username }}\",\"password\":\"{{ .password }}\",\"auth\":\"{{ $auth }}\"}}}"
  data:
    - secretKey: registry
      remoteRef:
        key: tenants/8e31b964/app/main/notes/registry
        property: registry
    - secretKey: username
      remoteRef:
        key: tenants/8e31b964/app/main/notes/registry
        property: username
    - secretKey: password
      remoteRef:
        key: tenants/8e31b964/app/main/notes/registry
        property: password
