apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notes-app-secrets
  namespace: ghc-nsp-8e31b964-main-notes
spec:
  refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: SecretStore
    name: ghc-ss-8e31b964-notes
  target:
    name: notes-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: session_secret
      remoteRef:
        key: tenants/8e31b964/app/main/notes/app
        property: session_secret
    - secretKey: bootstrap_admin_password
      remoteRef:
        key: tenants/8e31b964/app/main/notes/app
        property: bootstrap_admin_password
