apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notes
spec:
  chart:
    spec:
      version: "0.1.0-sha.7841795"
  values:
    host: notes.8e31b964.dev.gh0stcloud.de
    backend:
      image:
        repository: ghcr.io/empireforge-ef/notes-backend
        tag: sha-cc8c3be
    frontend:
      image:
        repository: ghcr.io/empireforge-ef/notes-frontend
        tag: sha-cc8c3be
