apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghc-nsp-8e31b964-main-notes

resources:
  - ../../../../base/notes
  - externalsecret-registry.yaml
  - externalsecret-db.yaml
  - externalsecret-app.yaml
  - postgres.yaml

patches:
  - path: helm-values.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: notes
