apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghc-nsp-8e31b964-main-notes
resources:
  - helmrelease.yaml
patches:
  - path: helm-values.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: notes
      version: v2
